### ISSUE TITLE
Can't load plug-in

### ISSUE THREAD

**Issue by VerbeekJordy** [kaiserdj/Darkorbit-client#11] opened 2021-02-27 17:06 UTC
When I open Hangar or when I click start I get the message that it can't load the plugin. I'm using Mac OS.
<img width="739" alt="Schermafbeelding 2021-02-27 om 18 06 22" src="https://user-images.githubusercontent.com/65980958/109394279-80b51000-7926-11eb-8347-264c86504e01.png">

**Comment by kaiserdj** [comment] 2021-02-27 17:27
Do you have the latest version of the client?

**Comment by enesbcs** [comment] 2021-02-27 19:49
Its the same on Ubuntu Linux: can not load plugin.
I guess that flash player is not available.

**Comment by enesbcs** [comment] 2021-02-27 20:01
Issue is duplicate of https://github.com/kaiserdj/Darkorbit-client/issues/10

**Comment by enesbcs** [comment] 2021-02-27 20:50
I've tried with Ubuntu Linux and as i see in core.js "this.ppapi_flash_path" var contains "Darkorbit-client/node_modules/electron/dist/resources/flash/libpepflashplayer.so" but file is located in "Darkorbit-client/flash/libpepflashplayer.so".
I've created Darkorbit-client/node_modules/electron/dist/resources/flash/ directory and copied libpepflashplayer.so file inside it, then Darkorbit Hangar and Game window opens fine.

**Comment by celikfatih** [comment] 2021-02-28 11:10
The problem was resolved for me when I did the following for Linux Ubuntu 18.04.
The following line in `core.js`:
`this.ppapi_flash_path = path.join(process.resourcesPath, './flash/libpepflashplayer.so');`
i changed it with this:
`this.ppapi_flash_path = path.join(app.getAppPath(), './flash/libpepflashplayer.so');`

**Comment by kaiserdj** [comment] 2021-02-28 12:16
Are you using the copied version (appimage) or have you cloned the repository? @celikfatih @enesbcs

**Comment by enesbcs** [comment] 2021-02-28 13:23
> And what version are you using?
Cloned version, the latest.
https://github.com/kaiserdj/Darkorbit-client/blob/main/core.js

@celikfatih has a point as win32 and darwin port already uses "app.getAppPath()" only the linux port uses "process.resourcesPath" which seems to be incorrect.

**Comment by kaiserdj** [comment] 2021-02-28 13:59
The problem in linux is that the format I use is appimage, which generates a temporary folder where it extracts the entire program, so I need the variable "process.resourcesPath"
Example of running result of appimage:
![image](https://user-images.githubusercontent.com/5487950/109420782-82d5a800-79d4-11eb-9c74-39a85c29531b.png)
But when you try to run from the project itself it returns the default environment that electron uses to run the projects
Project execution example:
![image](https://user-images.githubusercontent.com/5487950/109420848-d0521500-79d4-11eb-91f6-adcbe2c9997c.png)
Which does not exist

The solution I can think of is to check if the process.resourcesPath is in the tmp folder and if not, use app.getAppPath ()
`this.ppapi_flash_path = path.join(process.resourcesPath.split("/")[1] === "tmp" ? process.resourcesPath : app.getAppPath(), './flash/libpepflashplayer.so');`

I have checked it in Ubuntu, but not in the other distributions

**Comment by kaiserdj** [comment] 2021-02-28 14:05
Also this is for linux users(@enesbcs , @celikfatih y https://github.com/kaiserdj/Darkorbit-client/issues/10), but this issue is from a mac user, so the problem is not solved until you give more information

**Comment by kaiserdj** [comment] 2021-02-28 15:38
This https://github.com/kaiserdj/Darkorbit-client/commit/667b0938ebde6b5eb785465fd7f048009606a1b3 may fix @VerbeekJordy's error, but I don't have enough information to know what error you have.

**Comment by kaiserdj** [comment] 2021-03-04 13:49
I close the issue for not receiving a reply, if they have problems again. Reopen this issue or create a new one

**Closed by kaiserdj** 2021-03-04 13:49 UTC
Labels: Needs more information
