### ISSUE TITLE
Shortcuts are hooked when not in focus

### ISSUE THREAD

**Issue by Ionic97** [kaiserdj/Darkorbit-client#8] opened 2021-02-27 02:19 UTC
The keyboard shortcuts in 2.1.1 are hooked, even when the application is not in focus. This prevents the use of F5, Ctrl ++ and Ctrl +- while the client is open. Could an exception be implemented to check for window focus or mouse hover etc?

Also thank you very much for the last update :) You're doing pretty fast work on here.

**Comment by kaiserdj** [comment] 2021-02-27 11:32
The problem is that the native api of electron is [globalShortcut](https://www.electronjs.org/docs/api/global-shortcut).

Note from api:
> Note: The shortcut is global; it will work even if the app does not have the keyboard focus. This module cannot be used before the ready event of the app module is emitted.

What I will do is change from globalShortcut to web APIs, so it does not block other applications and only acts when it has focus

**Comment by kaiserdj** [comment] 2021-02-27 11:35
With this change it should be fixed.

If you have problems again, reopen the issue

Thank you very much for telling me the problem ❤️

**Closed by kaiserdj** 2021-02-27 11:35 UTC
